spring:
  application:
    name: ai_tracker
  data:
    mongodb:
      uri: mongodb://admin:password@localhost:27017/ai_tracker?authSource=admin
  profiles:
    default: "local"

openai:
  api:
    key: "" # This will be overridden by application-local.yml or environment variables

file:
  storage:
    enabled: true # Set to true to enable file storage
    directory: ./prompts