¬spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: sd
    password: sd
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 11240
